### ISSUE TITLE
doc: state whether or not rows need to be closed

### ISSUE THREAD

**Issue by shaunc** [joho/sqltocsv#12]
The documentation includes an example of using query rows without `defer rows.Close()` -- glancing at the code, this doesn't seem correct, but perhaps I'm wrong. Either way, the doc should say.

Thanks for the package!

**Comment by joho** [comment]
Thanks. You're right. I'd hoped/assumed people would see the use of `rows, _` and know that the examples were in YOLO mode and shouldn't be straight copy/pasted.

Expanded one of the examples to show the right behaviour and added a caveat.

**Comment by shaunc** [comment]
Thanks! I'm relatively new to go. I thought that perhaps you could be closing on the inside at first, though that would be against the standard convention.
